### ISSUE TITLE
NullPointerException when in a snowy biome

### ISSUE THREAD

**Issue by spoorn** [Snownee/Jade#121]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

5.99.4

### Modloader version

0.14.6

### Modpack info

https://www.curseforge.com/minecraft/modpacks/spoornpack-fabric

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Crashes when I went to a snowy biome:

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8321(net.minecraft.class_2338)" because "world" is null
	at snownee.snow.block.SnowVariant.getRaw(SnowVariant.java:21)
	at snownee.snow.block.SnowVariant.getPickedStack(SnowVariant.java:39)
	at snownee.jade.util.ClientPlatformProxy.getBlockPickedResult(ClientPlatformProxy.java:195)
	at snownee.jade.impl.BlockAccessorImpl.getPickedResult(BlockAccessorImpl.java:76)
	at snownee.jade.impl.BlockAccessorImpl._getIcon(BlockAccessorImpl.java:88)
	at snownee.jade.overlay.RayTracing.getIcon(RayTracing.java:162)
	at snownee.jade.overlay.TooltipRenderer.<init>(TooltipRenderer.java:28)
	at snownee.jade.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:145)
	at snownee.jade.util.ClientPlatformProxy.onClientTick(ClientPlatformProxy.java:142)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$dje000$onEndTick(class_310.java:17472)
	at net.minecraft.class_310.method_1574(class_310.java:1817)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by spoorn** [comment]
Sorry I just noticed the top of the stacktrace is from SnowRealMagic, but it does involve Jade and you own both the mods
