### ISSUE TITLE
1.20 update changes don't make sense

### ISSUE THREAD

**Issue by JaisDK** [Snownee/Jade#257]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.0.3

### Modloader version

Forge: 47.0.1

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

What's this now in 1.20?

![image](https://github.com/Snownee/Jade/assets/15868585/f003e573-f309-4315-90fd-dc9fbdec1969)
![image](https://github.com/Snownee/Jade/assets/15868585/36d37cf1-5131-4038-afff-d127361786ee)

**Comment by JaisDK** [comment]
```
public class ProductiveBeeProvider implements IEntityComponentProvider, IServerDataProvider<Entity>
{
    public static final ResourceLocation UID = new ResourceLocation(ProductiveBees.MODID, "productive_bee");
    public static final ProductiveBeeProvider INSTANCE = new ProductiveBeeProvider();

    public ProductiveBeeProvider() {
    }

    @Override
    public void appendTooltip(ITooltip tooltip, EntityAccessor accessor, IPluginConfig config) {
        if (config.get(ProductiveBeesWailaPlugin.BEE_ATTRIBUTES) && accessor.getServerData().contains("isProductiveBee")) {
            List<Component> list =  new ArrayList<>();
            BeeHelper.populateBeeInfoFromTag(accessor.getServerData(), list);
            for (Component component: list) {
                tooltip.add(component);
            }
        }
    }

    @Override
    public void appendServerData(CompoundTag compoundTag, Entity entity) {
        if (entity instanceof ProductiveBee bee) {
            bee.saveWithoutId(compoundTag);
            compoundTag.putBoolean("isProductiveBee", true);
            AdvancedBeehiveBlockEntityAbstract.removeIgnoredTags(compoundTag);
        }
    }

    @Override
    public ResourceLocation getUid() {
        return UID;
    }
}
```

**Comment by Snownee** [comment]
Hello, please read this: https://jademc.readthedocs.io/en/latest/changes/120/

**Comment by JaisDK** [comment]
Thanks! I thought I had tried that.

**Comment by JaisDK** [comment]
there's an error being thrown in dev by Jade

```
[13:36:58] [Worker-Main-5/ERROR] [Jade/]: Failed to load example plugin
java.lang.NoClassDefFoundError: snownee/jade/test/ExamplePlugin
	at snownee.jade.Jade.loadComplete(Jade.java:32) ~[jade-324717-4573193_mapped_official_1.20.1.jar%23197!/:11.0.3] {re:classloading}
	at snownee.jade.util.CommonProxy.loadComplete(CommonProxy.java:134) ~[jade-324717-4573193_mapped_official_1.20.1.jar%23197!/:11.0.3] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%23113!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%23113!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%23113!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%23113!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.20.1-47.0.1.jar%23190!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.20.1-47.0.1.jar%23193!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: java.lang.ClassNotFoundException: snownee.jade.test.ExamplePlugin
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.6.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.6.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 15 more
```

**Comment by Snownee** [comment]
Does it crash the game?

**Comment by JaisDK** [comment]
no

**Comment by Snownee** [comment]
Thanks for letting me know. I will try to avoid the error in the future
