### ISSUE TITLE
Forge 36.0.48 crashes on Jade 1.16.4-2.6.0

### ISSUE THREAD

**Issue by mariquit** [Snownee/Jade#34]
* Minecraft Version: 1.16.5
* Mod Version: 1.16.4-2.6.0

```[00:43:29] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.0.48, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --allowUpdates, false, --nogui]
[00:43:29] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_282 by AdoptOpenJDK
[00:43:29] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[00:43:29] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/john/1.16.5-36.0.48/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER
[00:43:30] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., --allowUpdates, false, --nogui]
[00:43:35] [modloading-worker-1/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 36.0.48, for MC 1.16.5 with MCP 20210115.111550
[00:43:35] [modloading-worker-1/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v36.0.48 Initialized
[00:43:35] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: Global Forge version check system disabled, no further processing.
[00:43:35] [modloading-worker-3/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class mcp/mobius/waila/overlay/tooltiprenderers/TextTooltipRenderer for invalid dist DEDICATED_SERVER
[00:43:35] [modloading-worker-3/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: Attempted to load class mcp/mobius/waila/overlay/tooltiprenderers/TextTooltipRenderer for invalid dist DEDICATED_SERVER
        Index: 1
        Listeners:
                0: NORMAL
                1: net.minecraftforge.eventbus.EventBus$$Lambda$2638/0x0000000000000000@8ad86de4
java.lang.RuntimeException: Attempted to load class mcp/mobius/waila/overlay/tooltiprenderers/TextTooltipRenderer for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
        at mcp.mobius.waila.addons.core.PluginCore.register(PluginCore.java:47)
        at mcp.mobius.waila.Waila.loadComplete(Waila.java:83)
        at mcp.mobius.waila.Waila$$Lambda$2932/0x0000000000000000.accept(Unknown Source)
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at net.minecraftforge.eventbus.EventBus$$Lambda$2638/0x0000000000000000.invoke(Unknown Source)
        at net.minecraftforge.eventbus.EventBus$$Lambda$2512/0x0000000000000000.invoke(Unknown Source)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
        at net.minecraftforge.fml.ModContainer$$Lambda$2775/0x0000000000000000.run(Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

[00:43:35] [modloading-worker-3/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event FMLLoadCompleteEvent dispatch for modid waila
java.lang.RuntimeException: Attempted to load class mcp/mobius/waila/overlay/tooltiprenderers/TextTooltipRenderer for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.0.48.jar:36.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:881) ~[?:1.8.0_282] {}
        at mcp.mobius.waila.addons.core.PluginCore.register(PluginCore.java:47) ~[jade:2.6.0] {re:classloading}
        at mcp.mobius.waila.Waila.loadComplete(Waila.java:83) ~[jade:2.6.0] {re:classloading}
        at mcp.mobius.waila.Waila$$Lambda$2932/0x0000000000000000.accept(Unknown Source) ~[?:?] {}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus$$Lambda$2638/0x0000000000000000.invoke(Unknown Source) ~[?:?] {}
        at net.minecraftforge.eventbus.EventBus$$Lambda$2512/0x0000000000000000.invoke(Unknown Source) ~[?:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) [forge:36.0] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) [forge:?] {re:classloading}
        at net.minecraftforge.fml.ModContainer$$Lambda$2775/0x0000000000000000.run(Unknown Source) [forge:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_282] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) [?:1.8.0_282] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_282] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_282] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_282] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_282] {}
[00:43:35] [main/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event COMPLETE, 1 errors found
[00:43:35] [main/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID dcc95ae5-9e8b-4e2a-87cb-fe685c78e6c7
[00:43:35] [main/INFO] [STDOUT/]: [net.minecraft.crash.CrashReport:func_85057_a:196]: Negative index in crash report handler (17/20)
[00:43:35] [main/FATAL] [ne.mi.fm.se.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2021-03-14_00.43.35-fml.txt
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 3/14/21 12:43 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
        at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) [forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) [?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282] {}
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) [forge-1.16.5-36.0.48.jar:36.0] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider$$Lambda$427/0x0000000000000000.call(Unknown Source) [forge-1.16.5-36.0.48.jar:36.0] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.0.48.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.0.48.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.0.48.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.0.48.jar:36.0] {}
-- MOD waila --
Details:
        Mod File: Jade-1.16.4-2.6.0.jar
        Failure message: Waila (Jade) (waila) encountered an error during the complete event phase
                java.lang.RuntimeException: Attempted to load class mcp/mobius/waila/overlay/tooltiprenderers/TextTooltipRenderer for invalid dist DEDICATED_SERVER
        Mod Version: 2.6.0
        Mod Issue URL: NOT PROVIDED
        Exception message: java.lang.RuntimeException: Attempted to load class mcp/mobius/waila/overlay/tooltiprenderers/TextTooltipRenderer for invalid dist DEDICATED_SERVER
Stacktrace:
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.0.48.jar:36.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:881) ~[?:1.8.0_282] {}
        at mcp.mobius.waila.addons.core.PluginCore.register(PluginCore.java:47) ~[jade:2.6.0] {re:classloading}
        at mcp.mobius.waila.Waila.loadComplete(Waila.java:83) ~[jade:2.6.0] {re:classloading}
        at mcp.mobius.waila.Waila$$Lambda$2932/0x0000000000000000.accept(Unknown Source) ~[?:?] {}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus$$Lambda$2638/0x0000000000000000.invoke(Unknown Source) ~[?:?] {}
        at net.minecraftforge.eventbus.EventBus$$Lambda$2512/0x0000000000000000.invoke(Unknown Source) ~[?:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.0] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModContainer$$Lambda$2775/0x0000000000000000.run(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_282] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_282] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_282] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_282] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_282] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_282] {}


-- System Details --
Details:
        Minecraft Version: 1.16.5
        Minecraft Version ID: 1.16.5
        Operating System: Linux (amd64) version 5.4.0-66-generic
        Java Version: 1.8.0_282, AdoptOpenJDK
        Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Linux amd64-64-Bit 20210120_869 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - ab07c6a8fd based on jdk8u282-b08), Eclipse OpenJ9
        Memory: 10875692896 bytes (10371 MB) / 12884901888 bytes (12288 MB) up to 12884901888 bytes (12288 MB)
        CPUs: 4
        JVM Flags: 11 total; -Xoptionsfile=/home/john/jdk8u282-b08/jre/lib/amd64/default/options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -Xmx12G -Xms12G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
        ModLauncher: 8.0.9+86+master.3cf110c
        ModLauncher launch target: fmlserver
        ModLauncher naming: srg
        ModLauncher services:
                /mixin-0.8.2.jar mixin PLUGINSERVICE
                /eventbus-4.0.0.jar eventbus PLUGINSERVICE
                /forge-1.16.5-36.0.48.jar object_holder_definalize PLUGINSERVICE
                /forge-1.16.5-36.0.48.jar runtime_enum_extender PLUGINSERVICE
                /accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE
                /forge-1.16.5-36.0.48.jar capability_inject_definalize PLUGINSERVICE
                /forge-1.16.5-36.0.48.jar runtimedistcleaner PLUGINSERVICE
                /mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE
                /forge-1.16.5-36.0.48.jar fml TRANSFORMATIONSERVICE
        FML: 36.0
        Forge: net.minecraftforge:36.0.48
        FML Language Providers:
                javafml@36.0
                minecraft@1
        Mod List:
                forge-1.16.5-36.0.48-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
                forge-1.16.5-36.0.48-universal.jar                |Forge                         |forge                         |36.0.48             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
                Jade-1.16.4-2.6.0.jar                             |Jade                          |jade                          |2.6.0               |DONE      |NOSIGNATURE
        Crash Report UUID: dcc95ae5-9e8b-4e2a-87cb-fe685c78e6c7[00:43:35] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Waila (Jade) (waila) encountered an error during the complete event phase
?7java.lang.RuntimeException: Attempted to load class mcp/mobius/waila/overlay/tooltiprenderers/TextTooltipRenderer for invalid dist DEDICATED_SERVER
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.finishMods(ModLoader.java:218) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:46) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) [?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282] {}
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) [forge-1.16.5-36.0.48.jar:36.0] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider$$Lambda$427/0x0000000000000000.call(Unknown Source) [forge-1.16.5-36.0.48.jar:36.0] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.0.48.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.0.48.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.0.48.jar:?] {}
```

**Comment by mariquit** [comment]
Same error on Forge 36.0.55
