### ISSUE TITLE
Incompatibility with 1.20.1 Natural Progression after Jade 1.6.3

### ISSUE THREAD

**Issue by D0CTOR-ZED** [Snownee/Jade#351]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

1.6.4, 1.7.0, 1.7.1

### Modloader version

Forge 47.2.19

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

When upgrading Jade for minecraft 1.20.1 from 11.6.3 to any later version 11.6.4, 11.7.0, 11.7.1, there is an incompatibility with the mod Natural Progression. The two mods together cause Natural Progression, when just looking at a stone block, to act as it expects to when a player tries to break a stone block with an unapproved tool. A stack trace during the PlayerEvent.BreakSpeed shows jade calling getDestroyProgress (m_60625) which I believe is the trigger for the issue. 

Change where the call is added as line 87:
https://github.com/Snownee/Jade/commit/a696198c615ad1b8f8a81069840a56ed5680c492

How Natural Progression handles stone breaking:
https://github.com/oitsjustjose/Natural-Progression/blob/5ddb02f2017ecea8837e2e6ca7d49724c9a41575/src/main/java/com/oitsjustjose/natprog/common/event/block/StoneBreak.java#L36

Part of the stack trace:
```
    at TRANSFORMER/forge@47.2.14/net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:189)
    at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.getDigSpeed(Player.java:721)
    at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour.m_5880_(BlockBehaviour.java:370)
    at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60625_(BlockBehaviour.java:641)
    at TRANSFORMER/jade@11.7.1/snownee.jade.JadeClient.drawBreakingProgress(JadeClient.java:237)
    at TRANSFORMER/jade@11.7.1/snownee.jade.overlay.OverlayRenderer.lambda$renderOverlay$0(OverlayRenderer.java:209)
    at TRANSFORMER/jade@11.7.1/snownee.jade.impl.CallbackContainer.call(CallbackContainer.java:28)
    at TRANSFORMER/jade@11.7.1/snownee.jade.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:208)
    at TRANSFORMER/jade@11.7.1/snownee.jade.overlay.OverlayRenderer.renderOverlay478757(OverlayRenderer.java:149)
    at TRANSFORMER/jade@11.7.1/snownee.jade.util.ClientProxy.onRenderTick(ClientProxy.java:163)
```

**Comment by D0CTOR-ZED** [comment]
I should have added that the stack trace was triggered by me to find why the break speed event was getting called.  The interaction doesn't cause a crash.

**Comment by Snownee** [comment]
not my fault.
