### ISSUE TITLE
Error with Gravestone `Error loading plugin at de.maxhenkel.gravestone.integration.waila.PluginGraveStone java.lang.NoSuchMethodError: 'void snownee.jade.api.IWailaClientRegistration.registerBlockComponent(snownee.jade.api.IBlockComponentProvider, java.lang.Class)'`

### ISSUE THREAD

**Issue by Lolothepro** [Snownee/Jade#430]
### Mod loader

NeoForge

### Minecraft version

1.21

### Mod version

15.1.3+NeoForge

### Modloader version

21.0.76-beta

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://mclo.gs/nFKpoCb

### Issue description

```
Error loading plugin at de.maxhenkel.gravestone.integration.waila.PluginGraveStone
java.lang.NoSuchMethodError: 'void snownee.jade.api.IWailaClientRegistration.registerBlockComponent(snownee.jade.api.IBlockComponentProvider, java.lang.Class)'
	at TRANSFORMER/gravestone@1.21-1.0.15/de.maxhenkel.gravestone.integration.waila.PluginGraveStone.registerClient(PluginGraveStone.java:15) ~[gravestone-neoforge-1.21-1.0.15.jar%23172!/:1.21-1.0.15] {re:classloading}
	at TRANSFORMER/jade@15.1.3+neoforge/snownee.jade.util.CommonProxy.loadComplete(CommonProxy.java:462) ~[Jade-1.21-NeoForge-15.1.3.jar%23173!/:15.1.3+neoforge] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.1.jar%23163!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%23163!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.1.jar%23163!/:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:169) ~[loader-4.0.15.jar%23164!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.ModLoader.lambda$dispatchParallelEvent$4(ModLoader.java:172) ~[loader-4.0.15.jar%23164!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.15/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.15.jar%23164!/:4.0] {}
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) [?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) [?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?] {}
```

**Comment by Snownee** [comment]
please report to the mod author
